### ISSUE TITLE
Como equipo queremos mejorar el frontend (Grupo 2)

### ISSUE THREAD

**Issue by NoeliaVasquezCrespo** [sis313/sistema_II2022.frontend#16]
- [x] Coordinar y cambiar el color de fondo (4 hrs)
- [x] Coordinar la fuente a utilizar (2 hrs)
- [x] Mejorar el navbar (3 hrs)
- [x] Uniformizar los colores (4 hrs)

**Comment by Mauro8500** [comment]
- [x] Coordinar con los otros grupos acerca de formatos (4 hrs)
- [x] Coordinar fuentes y iconos a utilizar (2 hrs)
- [x] Mejorar interfaz (3 hrs)
- [x] Uniformizar los colores (4 hrs)
